# Generated by Django 3.1 on 2020-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200809_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(auto_created=True, default='<django.db.models.fields.CharField>-<django.db.models.fields.AutoField>', unique=True),
        ),
    ]
