# Generated by Django 3.1 on 2020-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200811_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>-<django.db.models.fields.AutoField>', unique=True),
        ),
    ]
